"""The theta interpolation and the shared scaffolding knobs (AGENTS.md §5).

Two responsibilities:

  - **Endpoint equivalence.** ``tests/unit/data/nn_updates_golden.json`` was
    generated by the PRE-merge two-endpoint code (``NNACHUpdate`` /
    ``NNPPOUpdate``, commit 32a25e3) and is never regenerated. Reproducing it
    is what licenses the claim that merging the endpoints into one
    theta-parameterized rule left ACH's numerics — and therefore the paper
    reproduction in docs/reproduce_report.md — untouched.
  - **The interpolation itself**: linearity in theta, endpoint short-circuits,
    knob validation, and the fidelity warnings.

The fixture comparison was originally written as bit-exact ``==``. It is now
compared to a tight tolerance, because bit-exactness is not portable across
machines — see ``GOLDEN_REL`` below for the measurement that set it. The
same-machine bit-exactness claims in this file (the probe-does-not-perturb and
n_epochs tests) still use ``torch.equal`` and are unaffected: both sides of
those comparisons are computed here, so reassociation cancels.
"""

from __future__ import annotations

import copy
import json
import sys
import warnings
from pathlib import Path

import pytest
import torch

from mjai.agents.mlp import MLPSharedActorCritic
from mjai.algos.nn_updates import NNActorCriticUpdate, safe_log
from mjai.algos.transition import Batch, Transition, make_batch
from mjai.algos.update_rule import ACHFidelityWarning, AlgoConfig
from mjai.utils import gpu_assert

TOOLS_DIR = Path(__file__).resolve().parents[2] / "tools"
if str(TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(TOOLS_DIR))

import gen_nn_golden  # noqa: E402

GOLDEN_PATH = Path(__file__).resolve().parent / "data" / "nn_updates_golden.json"
NUM_ACTIONS = 4
OBS = [0.3, -0.7, 1.0, 0.1]

# Tolerance for the pre-merge fixture.
#
# The fixture is an equivalence guard, and was originally asserted with ``==``.
# That is only reproducible on the machine that recorded it: float32 reductions
# reassociate with whichever BLAS kernel a box picks (AVX2 vs AVX-512, thread
# count, torch build), which moves the last two or three significant digits.
# The guard was therefore machine-locked — it failed on any other host, which
# AGENTS.md §5 classes as a bug to fix rather than tolerate.
#
# Measured on a host other than the fixture's (8 vCPU Cascade Lake, torch
# 2.11.0+cu128, CPU mode) over all 6 scenarios = 1793 recorded values:
#
#   parameters  1636 values, 99.1% still bit-exact, worst 1.7e-07 (1.4 eps)
#   stats        157 values, 66.9% still bit-exact, worst 5.3e-07 (4.4 eps)
#
# float32 eps is 1.19e-07, so the whole spread is a few ULP: arithmetic noise,
# not a numerical difference.
#
# The upper end was calibrated by mutation, not by eye — the structural bugs
# this fixture exists to catch, measured as worst relative deviation:
#
#   entropy term dropped (coef -> 0)     4.0e-03    <- the SMALLEST of them
#   grad clipping enabled (0 -> 1.0)     7.8e-01
#   advantage normalization flipped      1.3e+00
#   theta endpoint swapped (0 <-> 1)     1.9e+00
#
# 1e-5 therefore sits ~19x above the noise ceiling (headroom for hosts noisier
# than this one) and ~400x below the smallest real regression: three orders of
# clearance on each side. ``test_tolerance_still_rejects_a_structural_change``
# pins that lower bound so a future edit cannot quietly loosen it into
# uselessness.
#
# What this does NOT catch is a sub-percent nudge to a hyperparameter knob
# (entropy_coef +-1% moves values by only 1.3e-06). That is not what the
# fixture guards: the knobs are read FROM the fixture, so they cannot drift
# without the fixture drifting with them.
#
# GOLDEN_ABS covers values recorded as exactly 0.0 (e.g. clip_frac on the ACH
# arms), where a relative bound says nothing.
GOLDEN_REL = 1e-5
GOLDEN_ABS = 1e-8


@pytest.fixture(autouse=True)
def _cpu_mode():
    gpu_assert.reset_for_tests()
    gpu_assert.require_cpu()
    yield
    gpu_assert.reset_for_tests()


# ---- endpoint bit-exactness against the pre-merge fixture ----


def _golden() -> dict:
    return json.loads(GOLDEN_PATH.read_text(encoding="utf-8"))


def test_golden_fixture_is_present_and_covers_both_endpoints():
    """Guard the guard: a missing/emptied fixture must fail, not vacuously pass."""
    scenarios = _golden()["scenarios"]
    thetas = {sc["config"]["theta"] for sc in scenarios}
    assert {0.0, 1.0} <= thetas, "fixture must pin both endpoints"
    assert len(scenarios) >= 6


def _assert_reproduces(got: object, want: object, where: str) -> None:
    """Recursive compare: floats to ``GOLDEN_REL``/``GOLDEN_ABS``, all else exact.

    Structure stays strict — a changed length or a swapped type is a failure,
    not something a numeric tolerance may absorb. Non-float leaves (ints,
    bools, strings) are still compared with ``==``.
    """
    if isinstance(want, list):
        assert isinstance(got, list), f"{where}: expected a list, got {type(got).__name__}"
        assert len(got) == len(want), f"{where}: length {len(got)} != recorded {len(want)}"
        for i, (g, w) in enumerate(zip(got, want, strict=True)):
            _assert_reproduces(g, w, f"{where}[{i}]")
    elif isinstance(want, float):
        assert got == pytest.approx(
            want, rel=GOLDEN_REL, abs=GOLDEN_ABS
        ), f"{where}: {got!r} != recorded {want!r}"
    else:
        assert got == want, f"{where}: {got!r} != recorded {want!r}"


def _compare_to_fixture(want: dict, got: dict) -> None:
    """Assert ``got`` reproduces the scenario's recorded stats and parameters.

    Factored out of the test so the guard-the-guard test below can run it
    against a deliberately broken policy and require it to fail.
    """
    for i, (a, b) in enumerate(zip(want["expected"]["stats"], got["stats"], strict=True)):
        for key, value in a.items():
            if key == "extra":
                for ek, ev in value.items():
                    _assert_reproduces(b["extra"][ek], ev, f"{want['name']} step{i} extra.{ek}")
            else:
                _assert_reproduces(b[key], value, f"{want['name']} step{i} {key}")
    for pname, pvals in want["expected"]["params"].items():
        _assert_reproduces(got["params"][pname], pvals, f"{want['name']} parameter {pname}")


@pytest.mark.parametrize("index", range(len(_golden()["scenarios"])))
def test_unified_rule_reproduces_pre_merge_numerics(index: int):
    """Every recorded stat and every post-step parameter must be reproduced.

    Floats are held to ``GOLDEN_REL`` (a few ULP of float32 headroom, see the
    constant); everything else must match exactly. Telemetry keys the fixture
    does not carry may be added (the merge made ``grad_norm`` available on the
    PPO arms, which the old PPO endpoint never computed); removing or changing
    a recorded value fails — a missing key raises KeyError here.
    """
    want = _golden()["scenarios"][index]
    _compare_to_fixture(want, gen_nn_golden.run_scenario(want))


def test_tolerance_still_rejects_a_structural_change():
    """Guard the guard: ``GOLDEN_REL`` must separate float noise from real changes.

    A tolerance wide enough to pass anything licenses nothing. Dropping the
    entropy term is the SMALLEST structural regression measured against this
    fixture (4.0e-3 relative, ~400x the tolerance); coarser breakages —
    flipped advantage normalization, a swapped theta endpoint, enabled
    gradient clipping — move values by O(1). If someone widens GOLDEN_REL past
    the point where even this is absorbed, this test fails first.
    """
    scenarios = _golden()["scenarios"]
    want = next(sc for sc in scenarios if sc["config"].get("entropy_coef"))
    broken = copy.deepcopy(want)
    broken["config"]["entropy_coef"] = 0.0

    with warnings.catch_warnings():  # some arms warn about ACH fidelity by design
        warnings.simplefilter("ignore", ACHFidelityWarning)
        got = gen_nn_golden.run_scenario(broken)

    with pytest.raises(AssertionError):
        _compare_to_fixture(want, got)


# ---- the interpolation ----


def _policy(seed: int = 0) -> MLPSharedActorCritic:
    return MLPSharedActorCritic(
        obs_size=len(OBS), num_actions=NUM_ACTIONS, hidden_sizes=(16,), seed=seed
    )


def _clone_weights(src: MLPSharedActorCritic, dst: MLPSharedActorCritic) -> None:
    with torch.no_grad():
        for (_, p_src), (_, p_dst) in zip(
            src.named_parameters(), dst.named_parameters(), strict=True
        ):
            p_dst.copy_(p_src)


def _batch(n: int = 8) -> Batch:
    advs = [0.5, -0.5, 0.3, -0.9, 0.8, -0.2, 0.1, -0.7]
    ts = [
        Transition(
            obs=OBS,
            legal_actions=list(range(NUM_ACTIONS)),
            action=i % NUM_ACTIONS,
            logprob=safe_log(0.25 + 0.05 * (i % 3)),
            value=0.0,
            reward=0.0,
            return_=0.5 - 0.1 * i,
            advantage=advs[i % len(advs)],
        )
        for i in range(n)
    ]
    return make_batch(ts, num_actions=NUM_ACTIONS)


def _policy_loss_at(theta: float, reference: MLPSharedActorCritic) -> float:
    """One step at ``theta`` from ``reference``'s exact weights; return the loss."""
    p = _policy(seed=7)
    _clone_weights(reference, p)
    rule = NNActorCriticUpdate(p, AlgoConfig(theta=theta, learning_rate=1e-3, entropy_coef=0.0))
    return rule.step(_batch()).policy_loss


def test_policy_loss_is_linear_in_theta():
    """(1-theta)*L_ppo + theta*L_ach, evaluated from identical starting weights."""
    reference = _policy(seed=7)
    at_0 = _policy_loss_at(0.0, reference)
    at_1 = _policy_loss_at(1.0, reference)
    assert at_0 != pytest.approx(at_1), "endpoints must differ or the test proves nothing"
    for theta in (0.25, 0.5, 0.75):
        expected = (1.0 - theta) * at_0 + theta * at_1
        assert _policy_loss_at(theta, reference) == pytest.approx(expected, rel=1e-5)


def test_endpoints_short_circuit_the_other_term():
    """theta=0 never builds the ACH term; theta=1 never builds the PPO term."""
    ppo_stats = NNActorCriticUpdate(_policy(), AlgoConfig(theta=0.0)).step(_batch())
    assert "gate_off_frac" not in ppo_stats.extra
    ach_stats = NNActorCriticUpdate(_policy(), AlgoConfig(theta=1.0)).step(_batch())
    assert "gate_off_frac" in ach_stats.extra
    assert ach_stats.clip_frac == 0.0  # PPO's metric, undefined without the term
    mixed = NNActorCriticUpdate(_policy(), AlgoConfig(theta=0.5)).step(_batch())
    assert "gate_off_frac" in mixed.extra and mixed.clip_frac >= 0.0


def test_grad_norm_is_reported_at_every_theta():
    """Gradient scale is the scan's main confounder, so it is always logged."""
    for theta in (0.0, 0.5, 1.0):
        stats = NNActorCriticUpdate(_policy(), AlgoConfig(theta=theta)).step(_batch())
        assert stats.extra["grad_norm"] > 0.0


# ---- per-term gradient probe (debug telemetry for mixed-theta runs) ----


def test_term_grad_probe_reports_only_the_terms_that_exist():
    """0.0 for a term that was never built would read as a measured zero."""
    ppo = NNActorCriticUpdate(_policy(), AlgoConfig(theta=0.0, probe_term_grad_norms=True)).step(
        _batch()
    )
    assert ppo.extra["grad_norm_ppo"] > 0.0
    assert "grad_norm_ach" not in ppo.extra and "grad_cos_ppo_ach" not in ppo.extra

    ach = NNActorCriticUpdate(_policy(), AlgoConfig(theta=1.0, probe_term_grad_norms=True)).step(
        _batch()
    )
    assert ach.extra["grad_norm_ach"] > 0.0
    assert "grad_norm_ppo" not in ach.extra and "grad_cos_ppo_ach" not in ach.extra

    mixed = NNActorCriticUpdate(_policy(), AlgoConfig(theta=0.25, probe_term_grad_norms=True)).step(
        _batch()
    )
    assert mixed.extra["grad_norm_ppo"] > 0.0 and mixed.extra["grad_norm_ach"] > 0.0
    assert -1.0 - 1e-6 <= mixed.extra["grad_cos_ppo_ach"] <= 1.0 + 1e-6


def test_term_grad_probe_scales_by_the_theta_weight():
    """``_scaled`` is what enters the update: (1-theta)*|g_ppo| and theta*|g_ach|."""
    theta = 0.25
    stats = NNActorCriticUpdate(
        _policy(), AlgoConfig(theta=theta, probe_term_grad_norms=True)
    ).step(_batch())
    assert stats.extra["grad_norm_ppo_scaled"] == pytest.approx(
        (1.0 - theta) * stats.extra["grad_norm_ppo"], rel=1e-6
    )
    assert stats.extra["grad_norm_ach_scaled"] == pytest.approx(
        theta * stats.extra["grad_norm_ach"], rel=1e-6
    )


@pytest.mark.parametrize("theta", [0.0, 0.5, 1.0])
def test_term_grad_probe_does_not_perturb_the_update(theta: float):
    """The probe must be readable during a reproduction run without changing it.

    It reads the graph via torch.autograd.grad and never writes .grad, so the
    optimizer trajectory has to stay bit-identical with the probe on.
    """
    batch = _batch()
    off = _policy(seed=5)
    on = _policy(seed=5)
    _clone_weights(off, on)
    for policy, probe in ((off, False), (on, True)):
        rule = NNActorCriticUpdate(
            policy, AlgoConfig(theta=theta, learning_rate=1e-3, probe_term_grad_norms=probe)
        )
        for _ in range(3):
            rule.step(batch)
    for (_, a), (_, b) in zip(off.named_parameters(), on.named_parameters(), strict=True):
        assert torch.equal(a, b)


def test_theta_outside_unit_interval_is_rejected():
    for bad in (-0.1, 1.5):
        with pytest.raises(ValueError, match="theta must lie in"):
            AlgoConfig(theta=bad)


def test_n_epochs_below_one_is_rejected():
    with pytest.raises(ValueError, match="n_epochs must be"):
        AlgoConfig(n_epochs=0)


def test_n_epochs_equals_that_many_single_epoch_steps():
    """n_epochs=3 in one call == three calls at n_epochs=1, bit for bit."""
    batch = _batch()
    looped = _policy(seed=3)
    with warnings.catch_warnings():  # multi-epoch under theta=1 warns by design
        warnings.simplefilter("ignore", ACHFidelityWarning)
        NNActorCriticUpdate(looped, AlgoConfig(learning_rate=1e-3, n_epochs=3)).step(batch)
    repeated = _policy(seed=3)
    rule = NNActorCriticUpdate(repeated, AlgoConfig(learning_rate=1e-3))
    for _ in range(3):
        rule.step(batch)
    for (_, a), (_, b) in zip(looped.named_parameters(), repeated.named_parameters(), strict=True):
        assert torch.equal(a, b)


def test_unknown_optimizer_fails_loudly():
    with pytest.raises(ValueError, match="Unknown optimizer"):
        NNActorCriticUpdate(_policy(), AlgoConfig(theta=0.0, optimizer="rmsprop"))


def test_scaffolding_defaults_follow_ach_at_theta_zero():
    """PPO inherits ACH's scaffolding unless a knob is set (the merge's premise)."""
    rule = NNActorCriticUpdate(_policy(), AlgoConfig(theta=0.0))
    assert isinstance(rule.optimizer, torch.optim.SGD)
    assert rule.config.normalize_advantages is False
    assert rule.config.n_epochs == 1
